version: "3.9"
services:
  incidisfy-backend-gateway:
    image: backend/gateway:1.0
    container_name: incidisfy-backend-gateway
    restart: on-failure    
    build:      
      dockerfile: Dockerfile
      context: .
    ports:
      - "8080:8080"   
    networks:
      - fmba-bridge

networks:
  fmba-bridge:
    driver: bridge