version: "3.9"
services:
  mongodb:
    image: mongo:4.4
    container_name: mongodb
    hostname: mongodb
    restart: unless-stopped
    ports:
      - $MONGO_HOST_PORT:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_ROOT_PASSWORD
      - MONGO_INITDB_DATABASE=$MONGO_DB
      - MONGO_DB_USERNAME=$MONGO_DB_USERNAME
      - MONGO_DB_PASSWORD=$MONGO_DB_PASSWORD
    volumes:
      - db:/data/db/
      - db:/var/log/mongodb/
      - db:/docker-entrypoint-initdb.d/
    command: ["--bind_ip", "0.0.0.0"]

  app_anexo:    
    image: backend/app_anexo:1.0
    container_name: app_anexo
    restart: on-failure
    depends_on:
      - mongodb
    env_file: ./.env
    build: ./      
    ports:      
      - $APP_ANEXO_LOCAL_PORT:$APP_ANEXO_DOCKER_PORT
    environment:      
      - SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE=$MONGO_DB
      - SPRING_DATA_MONGODB_AUTO_INDEX_CREATION=$MONGO_AUTO_INDEX_CREATION
      - SPRING_DATA_MONGODB_HOST=$MONGO_DB
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_USERNAME=$MONGO_DB_USERNAME
      - SPRING_DATA_MONGODB_PASSWORD=$MONGO_DB_PASSWORD
      - SPRING_DATA_MONGODB_DATABASE=$MONGO_DB
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
  
volumes:
  db: